sets.exported={
    sub="Kam'lanaut's Shield",
    item="Earth Card",
    ammo="Chrono Arrow",
    item="Disto. Sphere",
    item="Copper Voucher",
    item="Disto. Sphere",
    item="Water Card",
    ammo="Quelling Bolt",
    item="Earth Card",
    item="Sublime Sushi",
    item="Disto. Sphere",
    item="Earth Card",
    item="Kitron Macaron",
    item="Trump Card Case",
    item="Toolbag (Shihe)",
    waist="Patentia Sash",
    sub="Fermion Sword",
    item="Trump Card",
    range="Gastraphetes",
    left_ring="Orvail Ring",
    item="Earth Card",
    item="Shihei",
    item="Earth Card",
    item="Pearlsack",
    left_ring="Echad Ring",
    item="SP Gobbie Key",
    sub="Mandau",
    body="Boneworker's Apn.",
    left_ring="Artificer's Ring",
    item="Thurible",
    item="Tableware Set",
    body="Chocobo Shirt",
    body={ name="Mirke Wardecors", augments={'"Quick Draw" ability delay -5','"Mag.Atk.Bns."+4',}},
    item="Thurible",
    item="Console",
    body="Loki's Kaftan",
    feet={ name="Founder's Greaves", augments={'VIT+6','Accuracy+11','"Mag.Atk.Bns."+8',}},
    body="Councilor's Garb",
    item="Myrtle Desk",
    item="Storage Slip 01",
    item="Storage Slip 02",
    item="Thurible",
    sub={ name="Vampirism", augments={'STR+10','INT+10','"Occult Acumen"+10','DMG:+15',}},
    body={ name="Souv. Cuirass +1", augments={'HP+65','STR+12','Accuracy+13',}},
    back={ name="Cichol's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Damage taken-5%',}},
    back="Camulus's Mantle",
    item="Storage Slip 03",
    item="Tarutaru Stool",
    item="Thurible",
    head="Decennial Crown +1",
    head={ name="Mochi. Hatsuburi +1", augments={'Enhances "Yonin" and "Innin" effect',}},
    neck="Faith Torque",
    sub="Excalibur",
    item="Storage Slip 20",
    ammo="Chrono Bullet",
    head="Hike Khat",
    item="Storage Slip 10",
    item="Bonewrk. Stall",
    item="Thurible",
    ammo="Living Bullet",
    hands={ name="Ryuo Tekko", augments={'STR+10','DEX+10','Accuracy+15',}},
    item="Thurible",
    item="Thurible",
    item="Storage Slip 12",
    item="Tarutaru Stool",
    neck="Ganesha's Mala",
    item="Atst. of Right.",
    item="Thurible",
    hands={ name="Souv. Handschuhs", augments={'HP+80','Enmity+7','Potency of "Cure" effect received +10%',}},
    item="Storage Slip 08",
    item="Storage Slip 07",
    item="Storage Slip 04",
    item="Vana'clock",
    sub="Kam'lanaut's Sword",
    item="Storage Slip 11",
    head={ name="Adhemar Bonnet", augments={'STR+10','DEX+10','Attack+15',}},
    ammo="Living Bullet",
    item="Storage Slip 14",
    item="Storage Slip 16",
    sub="Ossifier's Shield",
    back={ name="Camulus's Mantle", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','Weapon skill damage +10%',}},
    head="Protective Specs.",
    item="Jeunoan Flag",
    item="Storage Slip 19",
    item="Storage Slip 05",
    legs={ name="Souveran Diechlings", augments={'HP+80','Enmity+7','Potency of "Cure" effect received +10%',}},
    item="San d'Orian Flag",
    item="Storage Slip 21",
    item="Imperial Standard",
    left_ring="Flamma Ring",
    body={ name="Lanun Frac +3", augments={'Enhances "Loaded Deck" effect',}},
    item="Storage Slip 22",
    item="Storage Slip 13",
    item="Storage Slip 09",
    item="Storage Slip 15",
    item="Thurible",
    legs={ name="Cab. Breeches", augments={'Enhances "Invincible" effect',}},
    feet={ name="Cab. Leggings +1", augments={'Enhances "Guardian" effect',}},
    neck="Homeric Gorget",
    item="Storage Slip 17",
    waist="Creed Baudrier",
    sub={ name="Brilliance", augments={'Divine magic skill +12','Enmity+5','DMG:+9',}},
    sub={ name="Ochu", augments={'STR+8','DMG:+5',}},
    sub={ name="Rubicundity", augments={'Mag. Acc.+7','"Mag.Atk.Bns."+7','Dark magic skill +6','"Conserve MP"+4',}},
    body="Decennial Coat +1",
    sub="Sasuke Katana",
    sub="Kannagi",
    main="Verethragna",
    sub={ name="Rubicundity", augments={'Mag. Acc.+7','"Mag.Atk.Bns."+7','Dark magic skill +6','"Conserve MP"+4',}},
    range="Venery Bow",
    ammo="Plumose Sachet",
    hands={ name="Founder's Gauntlets", augments={'STR+1','Attack+7',}},
    feet={ name="Founder's Greaves", augments={'VIT+6','Accuracy+13',}},
    neck="Eddy Necklace",
    neck="Love Torque",
    main="Denouements",
    main={ name="Fleshcarvers", augments={'STR+10','DEX+10','"Store TP"+5','DMG:+10',}},
    sub="Acclimator",
    main="Dacnomania",
    main="Umaru",
    sub="Queller Rod",
    sub={ name="Nibiru Cudgel", augments={'MND+10','Mag. Acc.+15','"Cure" potency +15%',}},
    range={ name="Cibitshavore", augments={'STR+12','Rng.Acc.+10','"Store TP"+7',}},
    ammo="Focal Orb",
    ammo="Falcon Eye",
    range="Raider's Bmrng.",
    sub="Culminus",
    head="Terminal Helm",
    head="Glory Crown",
    head="Destrier Beret",
    body="Terminal Plate",
    body="Vatic Byrnie",
    body={ name="Souveran Cuirass", augments={'HP+80','Enmity+7','Potency of "Cure" effect received +10%',}},
    range="Molybdosis",
    item="Ardor Stone",
    item="Balance Card",
    item="Ardor Card",
    item="Ardor Coin",
    item="Balance Stone",
    item="Ardor Jewel",
    item="Wieldance Stone",
    item="Wieldance Coin",
    item="Voyage Card",
    item="Balance Jewel",
    item="Kukulkan's Fang",
    main={ name="Himetsuruichimonji", augments={'STR+10','Accuracy+10','Attack+10','Quadruple Attack +3',}},
    feet={ name="Mochi. Kyahan +1", augments={'Enh. Ninj. Mag. Acc/Cast Time Red.',}},
    item="Wieldance Jewel",
    item="Bukhis's Wing",
    sub={ name="Divinity", augments={'Attack+6','Accuracy+7','Phys. dmg. taken -2%','DMG:+10',}},
    item="Sh.Abjuration: Hd.",
    item="Vision Jewel",
    item="Wieldance Card",
    item="Snarled Goad",
    item="Ab.Abjuration: Lg.",
    item="Fistl. Discharge",
    range="Dynamis Bow",
    neck="Deviant Necklace",
    main="Honebami",
    item="Cipher: Rosulatia",
    body="Hydra Haubert",
    item="Gr.Abjuration: Ft.",
    item="Atst. of Legerity",
    sub={ name="Ochu", augments={'STR+6','DEX+5','Ninjutsu skill +5',}},
    sub={ name="Ochu", augments={'STR+5','DMG:+2',}},
    item="Bu.Abjuration: Hn.",
    sub={ name="Izuna", augments={'Attack+20','Crit. hit damage +3%','DMG:+15',}},
    item="Ulhuadshi's Fang",
    item="Va.Abjuration: Ft.",
    head="Sukeroku Hachi.",
    feet="Hachiryu Sune-Ate",
    item="Cy.Abjuration: Bd.",
    left_ear="Heartseeker Earring",
    left_ring="Shadow Ring",
    item="Tr.Abjuration: Ft.",
    item="Cr.Abjuration: Lg.",
    left_ear="Dudgeon Earring",
    item="Ve.Abjuration: Hn.",
    ammo="Sihirik",
    main="Soboro Sukehiro",
    item="Voyage Stone",
    hands={ name="Fanatic Gloves", augments={'MP+50','Healing magic skill +10','"Conserve MP"+7','"Fast Cast"+7',}},
    item="Ar.Abjuration: Ft.",
    item="Sh.Abjuration: Ft.",
    range="Loxley Bow",
    hands="Pursuer's Cuffs",
    ammo="Paeapua",
    item="Cipher: August",
    hands={ name="Adhemar Wristbands", augments={'AGI+10','Rng.Acc.+15','Rng.Atk.+15',}},
    item="Ve.Abjuration: Ft.",
    item="Cy.Abjuration: Ft.",
    neck="Iqabi Necklace",
    body={ name="Ryuo Domaru", augments={'HP+50','"Store TP"+5','"Dbl.Atk."+2',}},
    range="Holliday",
    sub={ name="Skinflayer", augments={'"Triple Atk."+2','Accuracy+24','Attack+22',}},
    back="Agema Cape",
    hands="Umuthi Gloves",
    item="Cipher: Ingrid II",
    item="Gr.Abjuration: Hd.",
    sub="Izhiikoh",
    sub={ name="Vampirism", augments={'STR+5','INT+5','DMG:+3',}},
    head="Taeon Chapeau",
    back="Fravashi Mantle",
    body={ name="Adhemar Jacket", augments={'DEX+10','AGI+10','Accuracy+15',}},
    sub="Shijo",
    main="Tsurumaru",
    sub="Shijo",
    legs={ name="Ryuo Hakama", augments={'HP+50','Accuracy+15','Attack+15',}},
    hands={ name="Adhemar Wristbands", augments={'DEX+10','AGI+10','Accuracy+15',}},
    item="Apademak Horn",
    item="Tr.Abjuration: Bd.",
    legs={ name="Valor. Hose", augments={'Attack+19','Weapon skill damage +3%','Accuracy+15',}},
    head={ name="Merlinic Hood", augments={'Mag. Acc.+16 "Mag.Atk.Bns."+16','Magic burst dmg.+9%','CHR+5','"Mag.Atk.Bns."+10',}},
    back="Tantalic Cape",
    item="Wind Cluster",
    sub="Thrace Strap",
    item="Bead Pouch",
    item="Copper Voucher",
    item="Wind Cluster",
    head={ name="Merlinic Hood", augments={'Mag. Acc.+9','"Fast Cast"+7','MND+8','"Mag.Atk.Bns."+10',}},
    sub="Niobid Strap",
    ammo="Quelling Bolt",
    item="Silt Pouch",
    item="Wind Cluster",
    item="P. RNG Card",
    item="Toolbag (Shika)",
    body="Herculean Vest",
    neck="Adad Amulet",
    head={ name="Amalric Coif", augments={'MP+60','INT+10','Enmity-5',}},
    left_ring="Craftmaster's Ring",
    item="Toolbag (Ino)",
    ammo="Thr. Tomahawk",
    head="Wh. Rarab Cap",
    body={ name="Herculean Vest", augments={'Rng.Acc.+8','Crit. hit damage +5%','DEX+10',}},
    sub={ name="Colada", augments={'"Dbl.Atk."+3','VIT+15','Accuracy+12','Attack+12','DMG:+14',}},
    main="Lathi",
    head={ name="Founder's Corona", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Magic dmg. taken -5%',}},
    sub="Emissary",
    hands={ name="Founder's Gauntlets", augments={'STR+7','Attack+12','"Mag.Atk.Bns."+10',}},
    sub={ name="Shigi", augments={'Accuracy+50','Rng.Acc.+50','Damage Taken -5%',}},
    head={ name="Merlinic Hood", augments={'"Mag.Atk.Bns."+15','Phys. dmg. taken -2%',}},
    sub="Loxotic Mace +1",
    body={ name="Mochi. Chainmail +1", augments={'Enhances "Sange" effect',}},
    item="Frayed Sack (H1)",
    legs={ name="Merlinic Shalwar", augments={'"Mag.Atk.Bns."+21','Damage taken-1%','CHR+10','Mag. Acc.+13',}},
    item="Frayed Sack (Pul)",
    left_ring="Mephitas's Ring",
    head="Jhakri Coronal +1",
    sub={ name="Sandung", augments={'Accuracy+50','Crit. hit rate+5%','"Triple Atk."+3',}},
    item="Maze Tabula M01",
    ammo="Ghastly Tathlum",
    hands={ name="Mochizuki Tekko +1", augments={'Enh. "Ninja Tool Expertise" effect',}},
    feet="Danzo Sune-Ate",
    head="Slime Cap",
    hands={ name="Merlinic Dastanas", augments={'"Mag.Atk.Bns."+26','Phys. dmg. taken -3%','DEX+5','Mag. Acc.+7',}},
    body={ name="Valorous Mail", augments={'Accuracy+22','"Store TP"+5','MND+6',}},
    legs="Warrior's Cuisses",
    neck="Bilious Torque",
    item="Sublime Sushi",
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10',}},
    legs="Tatena. Haidate",
    left_ring="Mephitas's Ring +1",
    hands={ name="Herculean Gloves", augments={'Attack+11','"Triple Atk."+3','DEX+13',}},
    body="Odyss. Chestplate",
    back={ name="Mecisto. Mantle", augments={'Cap. Point+47%','Mag. Acc.+2','DEF+6',}},
    head="Befouled Crown",
    body={ name="Amalric Doublet", augments={'MP+60','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    body="Jhakri Robe +1",
    back="Solemnity Cape",
    body="Spae. Coat +1",
    hands="Jhakri Cuffs +1",
    body="Merlinic Jubbah",
    back={ name="Yokaze Mantle", augments={'STR+3','DEX+1','Sklchn.dmg.+4%','Weapon skill damage +3%',}},
    item="Storage Slip 06",
    sub="Bloodrain Strap",
    item="Toolbag (Cho)",
    item="Toolbg. (Kaben)",
    item="Rem's Tale Ch.6",
    left_ring="Apate Ring",
    item="Mog Pell (Red)",
    head="Metal Slime Hat",
    item="Tr.Abjuration: Hd.",
    legs="Valor. Hose",
    item="Toolbag (Ino)",
    sub={ name="Kanaria", augments={'"Triple Atk."+3','STR+2','Accuracy+24','DMG:+12',}},
    item="SP Gobbie Key",
    body={ name="Found. Breastplate", augments={'Accuracy+13','Mag. Acc.+14','Attack+13','"Mag.Atk.Bns."+13',}},
    item="Atst. of Invuln.",
    main="Naglering",
    sub="Kustawi",
    sub={ name="Kanaria", augments={'"Triple Atk."+2','AGI+2','Accuracy+20','Attack+17','DMG:+5',}},
    item="Tinnin's Fang",
    item="Copper Voucher",
    hands={ name="Amalric Gages", augments={'INT+10','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    back="Mending Cape",
    item="Ar.Abjuration: Lg.",
    item="Ve.Abjuration: Hd.",
    item="Gr.Abjuration: Lg.",
    neck="Clotharius Torque",
    body={ name="Pursuer's Doublet", augments={'HP+50','Crit. hit rate+4%','"Snapshot"+6',}},
    legs={ name="Rao Haidate", augments={'STR+10','DEX+10','Attack+15',}},
    feet={ name="Psycloth Boots", augments={'MP+50','INT+7','"Conserve MP"+6',}},
    feet="Odyssean Greaves",
    item="Mog Pell (Silver)",
    body={ name="Odyss. Chestplate", augments={'Accuracy+19','Weapon skill damage +3%',}},
    sub="Priwen",
    left_ear="Gwati Earring",
    feet={ name="Souveran Schuhs", augments={'HP+50','Attack+20','Magic dmg. taken -3',}},
    left_ring="Globidonta Ring",
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    feet={ name="Founder's Greaves", augments={'VIT+10','Accuracy+15','"Mag.Atk.Bns."+15','Mag. Evasion+15',}},
    left_ring="Acumen Ring",
    back="Perimede Cape",
    range="Antitail +1",
    left_ear="Influx Earring",
    hands="Odyssean Gauntlets",
    back="Disperser's Cape",
    feet={ name="Odyssean Greaves", augments={'Accuracy+30','"Fast Cast"+5','DEX+9',}},
    back="Nexus Cape",
    ammo="Happo Shuriken",
    item="Abdhaljs Seal",
    legs={ name="Amalric Slops", augments={'MP+60','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    legs="Assid. Pants +1",
    hands={ name="Odyssean Gauntlets", augments={'DEX+1','Attack+3',}},
    sub="Ochain",
    legs={ name="Odyssean Cuisses", augments={'Accuracy+25','"Fast Cast"+5','Attack+14',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+16','Weapon skill damage +4%','DEX+6',}},
    ammo="Quelling Bolt",
    feet="Hattori Kyahan",
    back="Fi Follet Cape",
    left_ring="Bonecrafter's Ring",
    item="Wind Crystal",
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+11','"Fast Cast"+5','CHR+9',}},
    legs="Valor. Hose",
    feet={ name="Ryuo Sune-Ate", augments={'STR+10','Attack+20','Crit. hit rate+3%',}},
    sub="Tzacab Grip",
    item="Chonofuda",
    feet="Hachi. Kyahan +1",
    feet={ name="Adhemar Gamashes", augments={'DEX+10','AGI+10','Accuracy+15',}},
    feet="Tutyr Sabots",
    sub="Firetongue",
    legs={ name="Odyssean Cuisses", augments={'Accuracy+25 Attack+25','"Dbl.Atk."+3','Accuracy+9','Attack+1',}},
    item="Storage Slip 18",
    item="Hap. Sh. Pouch",
    feet={ name="Amm Greaves", augments={'HP+50','VIT+10','Accuracy+15','Damage taken-2%',}},
    neck="Ocachi Gorget",
    neck="Asperity Necklace",
    item="Inoshishinofuda",
    ammo="Togakushi Shuriken",
    feet="Manabyss Pigaches",
    item="Shikanofuda",
    left_ear="Calamitous Earring",
    neck="Anu Torque",
    neck="Empath Necklace",
    left_ring="K'ayres Ring",
    item="Abdhaljs Thread",
    ammo="Expeditious Pinion",
    item="Abdhaljs Dust",
    item="Abdhaljs Fiber",
    item="P. COR Card",
    item="Kyou's Scale",
    item="Abdhaljs Sap",
    item="P. WAR Card",
    item="P. WAR Card",
    item="Gin's Scale",
    ammo="Hydrocera",
    item="P. BLM Card",
    back="Xucau Mantle",
    ammo="Quelling Bolt",
    item="Kin's Scale",
    sub="Adapa Shield",
    item="P. PLD Card",
    sub="Metal Slime Shield",
    item="Fu's Scale",
    head="Hydra Salade",
    item="Abdhaljs Resin",
    main={ name="Bonesplitter", augments={'DMG:+13',}},
    item="Itzpapa. Scale",
    item="P. DRK Card",
    item="P. RNG Card",
    item="P. NIN Card",
    item="P. GEO Card",
    head={ name="Valorous Mask", augments={'Attack+18','"Dbl.Atk."+3','VIT+4','Accuracy+12',}},
    item="Lebondopt Wing",
    item="Vision Coin",
    item="Ardor Card",
    sub={ name="Ochu", augments={'STR+6','DEX+7','Ninjutsu skill +5','DMG:+9',}},
    item="P. RUN Card",
    item="Glavoid Shell",
    range="Wingcutter +1",
    item="Storage Slip 23",
    item="Abdhaljs Metal",
    head="Cumulus Masque",
    item="Kei's Scale",
    item="Abdhaljs Dust",
    left_ear="Dominance Earring",
    item="Vision Stone",
    ammo="Iron Gobbet",
    head="Mandra. Masque",
    item="Abdhaljs Sap",
    head={ name="Jumalik Helm", augments={'MND+3','"Mag.Atk.Bns."+7','Magic burst dmg.+5%',}},
    item="Abdhaljs Dye",
    ammo="Amar Cluster",
    body="Mandra. Suit",
    item="Abdhaljs Thread",
    item="Isgebind's Heart",
    item="Earth Cluster",
    feet={ name="Founder's Greaves", augments={'VIT+7','Accuracy+10','"Mag.Atk.Bns."+9','Mag. Evasion+10',}},
    item="Earth Cluster",
    item="Alfard's Fang",
    sub="Oneiros Knife",
    left_ear="Lempo Earring",
    item="Vision Card",
    item="Ardor Stone",
    item="Rose Scampi",
    item="Mellidopt Wing",
    left_ear="Hermetic Earring",
    item="Pulchridopt Wing",
    item="Baby Blobdingnag",
    item="Abdhaljs Seal",
    ammo="Quelling Bolt",
    feet={ name="Arcadian Socks +1", augments={'Enhances "Stealth Shot" effect',}},
    left_ring="Evanescence Ring",
    head={ name="Ryuo Somen", augments={'HP+50','Accuracy+15','Attack+15',}},
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    range={ name="Ataktos", augments={'Delay:+60','TP Bonus +1000',}},
    head="Flam. Zucchetto +2",
    head={ name="Dampening Tam", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Quadruple Attack +3',}},
    head={ name="Arcadian Beret +2", augments={'Enhances "Recycle" effect',}},
    body="Orion Jerkin +3",
    body="Laksa. Frac +3",
    head={ name="Adhemar Bonnet +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    body={ name="Valorous Mail", augments={'"Triple Atk."+1','INT+9','Quadruple Attack +2',}},
    body={ name="Adhemar Jacket +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    ammo="Seeth. Bomblet +1",
    legs={ name="Herculean Trousers", augments={'Accuracy+2','Weapon skill damage +4%','STR+7',}},
    head={ name="Herculean Helm", augments={'Accuracy+18','Weapon skill damage +4%','STR+3','Attack+9',}},
    neck="Erra Pendant",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    legs={ name="Samnuha Tights", augments={'STR+10','DEX+10','"Dbl.Atk."+3','"Triple Atk."+3',}},
    left_ring="Locus Ring",
    left_ear="Loquac. Earring",
    left_ear="Brutal Earring",
    feet={ name="Adhe. Gamashes +1", augments={'HP+65','"Store TP"+7','"Snapshot"+10',}},
    neck="Boneworker's Torque",
    neck="Regal Necklace",
    legs="Gyve Trousers",
    neck="Phalaina Locket",
    hands={ name="Adhemar Wrist. +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    head={ name="Herculean Helm", augments={'Rng.Acc.+14 Rng.Atk.+14','"Snapshot"+2','AGI+15','Rng.Acc.+1','Rng.Atk.+11',}},
    left_ring={ name="Dark Ring", augments={'Magic dmg. taken -5%','Phys. dmg. taken -4%',}},
    left_ring="Defending Ring",
    body={ name="Argosy Hauberk +1", augments={'STR+12','DEX+12','Attack+20',}},
    neck="Bathy Choker +1",
    legs={ name="Adhemar Kecks", augments={'AGI+10','"Rapid Shot"+10','Enmity-5',}},
    neck="Sanctity Necklace",
    neck="Erudit. Necklace",
    legs={ name="Taeon Tights", augments={'"Fast Cast"+5',}},
    waist="Flax Sash",
    body="Twilight Mail",
    left_ring="Perception Ring",
    head="Twilight Helm",
    waist="Hachirin-no-Obi",
    head="Pumm. Mask +1",
    hands={ name="Argosy Mufflers +1", augments={'STR+20','"Dbl.Atk."+3','Haste+3%',}},
    left_ring="Dim. Ring (Holla)",
    hands={ name="Agoge Mufflers +1", augments={'Enhances "Mighty Strikes" effect',}},
    feet="Pumm. Calligae +3",
    neck="Fotia Gorget",
    waist="Luminary Sash",
    left_ring="Sangoma Ring",
    left_ring="Patricius Ring",
    legs={ name="Argosy Breeches +1", augments={'STR+12','DEX+12','Attack+20',}},
    left_ring="Warp Ring",
    head={ name="Argosy Celata +1", augments={'DEX+12','Accuracy+20','"Dbl.Atk."+3',}},
    neck="Ygnas's Resolve +1",
    waist="Refoccilation Stone",
    neck="Magoraga Beads",
    waist="Siegel Sash",
    waist="Grunfeld Rope",
    body={ name="Herculean Vest", augments={'Accuracy+9','"Mag.Atk.Bns."+29','Mag. Acc.+17 "Mag.Atk.Bns."+17',}},
    left_ear="Cessance Earring",
    waist="Fotia Belt",
    neck="Diemer Gorget",
    back={ name="Belenus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10',}},
    left_ring="Petrov Ring",
    head="Redeyes",
    back="Segomo's Mantle",
    sub={ name="Vampirism", augments={'STR+3',}},
    hands="Serpentes Cuffs",
    legs={ name="Lengo Pants", augments={'INT+7','Mag. Acc.+8','"Mag.Atk.Bns."+7',}},
    legs={ name="Founder's Hose", augments={'MND+7','Mag. Acc.+10','Attack+10',}},
    feet={ name="Taeon Boots", augments={'Accuracy+16 Attack+16','"Triple Atk."+2','DEX+10',}},
    left_ear="Assuage Earring",
    neck="Subtlety Spec.",
    main="Ragnarok",
    sub={ name="Atoyac", augments={'Occ. atk. twice+8','"Mag.Atk.Bns."+10',}},
    feet="Wurrukatte Boots",
    sub="Gada",
    head={ name="Psycloth Tiara", augments={'----------------',}},
    left_ear="Lifestorm Earring",
    main="Akademos",
    main={ name="Humility", augments={'STR+1','Accuracy+3','Attack+5','DMG:+7',}},
    body="Sayadio's Kaftan",
    left_ear="Psystorm Earring",
    main="Conqueror",
    body="Abnoba Kaftan",
    range="Hangaku-no-Yumi",
    left_ear="Evans Earring",
    left_ring="Jalzahn's Ring",
    back="Segomo's Mantle",
    head={ name="Lilitu Headpiece", augments={'STR+5','DEX+5','Attack+5',}},
    left_ring="Nekhen Ring",
    head="Chironic Hat",
    head="Imp. Wing Hairpin",
    waist="Black Belt",
    back="Ankou's Mantle",
    back="Nantosuelta's Cape",
    sub="Kikoku",
    left_ring="Duodec. Ring",
    back="Ogma's cape",
    hands="Schutzen Mittens",
    sub={ name="Brilliance", augments={'Shield skill +7','Divine magic skill +10','Enmity+4','DMG:+10',}},
    main="Oatixur",
    left_ear="Cryptic Earring",
    head={ name="Adhemar Bonnet", augments={'DEX+10','AGI+10','Accuracy+15',}},
    feet="Serpentes Sabots",
    body={ name="Witching Robe", augments={'MP+25','"Mag.Atk.Bns."+7',}},
    body={ name="Rawhide Vest", augments={'DEX+10','STR+7','INT+7',}},
    waist="Hurch'lan Sash",
    head={ name="Argosy Celata", augments={'DEX+10','Accuracy+15','"Dbl.Atk."+2',}},
    back="Laic Mantle",
    legs={ name="Argosy Breeches", augments={'STR+10','DEX+10','Attack+15',}},
    back="Impassive Mantle",
    body={ name="Jumalik Mail", augments={'HP+50','Attack+15','Enmity+9','"Refresh"+2',}},
    range="Annihilator",
    back="Shadow Mantle",
    range="Death Penalty",
    left_ring="Metamorph Ring",
    body={ name="Argosy Hauberk", augments={'STR+10','DEX+10','Attack+15',}},
    left_ear="Steelflash Earring",
    hands="Valorous Mitts",
    left_ear="Bladeborn Earring",
    waist="Sarissapho. Belt",
    waist="Famine Sash",
    sub="Aegis",
    legs={ name="Odyssean Cuisses", augments={'Accuracy+25','Weapon skill damage +3%','Attack+12',}},
    left_ear="Ethereal Earring",
    left_ring="Apeile Ring +1",
    feet={ name="Odyssean Greaves", augments={'Accuracy+29','"Dbl.Atk."+2','STR+7','Attack+1',}},
    left_ring="Fortified Ring",
    hands="Iga Tekko +2",
    neck="Yarak Torque",
    ammo="Honed Tathlum",
    feet={ name="Odyssean Greaves", augments={'Attack+28','Potency of "Cure" effect received+6%','AGI+5','Accuracy+1',}},
    legs={ name="Herculean Trousers", augments={'Mag. Acc.+17','Weapon skill damage +3%','STR+1','"Mag.Atk.Bns."+11',}},
    main={ name="Zulfiqar", augments={'"Dbl.Atk."+2','DEX+11','Accuracy+15','DMG:+19',}},
    hands="Odyssean Gauntlets",
    neck="Unmoving Collar",
    legs={ name="Souv. Diechlings +1", augments={'STR+12','VIT+12','Accuracy+20',}},
    feet={ name="Lanun Bottes +3", augments={'Enhances "Wild Card" effect',}},
    legs="Osmium Cuisses",
    back="Cichol's Mantle",
    legs={ name="Mochi. Hakama +1", augments={'Enhances "Mijin Gakure" effect',}},
    left_ring="Apeile Ring",
    body="Hiza. Haramaki +1",
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    body="Chasseur's Frac +1",
    hands="Chasseur's Gants +1",
    left_ear="Suppanomimi",
    hands={ name="Floral Gauntlets", augments={'Rng.Acc.+15','Accuracy+15','"Triple Atk."+3','Magic dmg. taken -4%',}},
    back="Navarch's Mantle",
    legs="Hiza. Hizayoroi +1",
    hands={ name="Helios Gloves", augments={'"Fast Cast"+5',}},
    body="Pumm. Lorica +3",
    body={ name="Samnuha Coat", augments={'Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+5','"Dual Wield"+5',}},
    body="Boii Lorica",
    left_ear="Hecate's Earring",
    hands="Boii Mufflers",
    body={ name="Herculean Vest", augments={'Rng.Atk.+15','Weapon skill damage +4%','AGI+10',}},
    left_ring="Archon Ring",
    feet={ name="Lustratio Leggings", augments={'HP+50','STR+10','DEX+10',}},
    legs={ name="Lustratio Subligar", augments={'HP+50','Attack+25','Enmity-5',}},
    waist="Channeler's Stone",
    left_ear="Infused Earring",
    waist="Gishdubar Sash",
    neck="Caro Necklace",
    waist="Fucho-no-Obi",
    neck="Loricate Torque +1",
    back={ name="Bane Cape", augments={'Elem. magic skill +7','Dark magic skill +10',}},
    left_ear="Nourish. Earring +1",
    hands={ name="Emi. Gauntlets +1", augments={'HP+65','DEX+12','Accuracy+20',}},
    left_ear="Barkaro. Earring",
    hands={ name="Lanun Gants", augments={'Enhances "Fold" effect',}},
    back={ name="Gunslinger's Cape", augments={'Enmity-1','"Mag.Atk.Bns."+1','"Phantom Roll" ability delay -2','Weapon skill damage +3%',}},
    left_ring="Epona's Ring",
    back={ name="Cichol's Mantle", augments={'VIT+20','Accuracy+20 Attack+20','VIT+10','"Dbl.Atk."+10',}},
    body={ name="Agoge Lorica", augments={'Enhances "Aggressive Aim" effect',}},
    feet="Sulev. Leggings +2",
    body={ name="Merlinic Jubbah", augments={'"Fast Cast"+5',}},
    head={ name="Lanun Tricorne", augments={'Enhances "Winning Streak" effect',}},
    head="Chass. Tricorne +1",
    hands={ name="Odyssean Gauntlets", augments={'Weapon skill damage +4%','Accuracy+14',}},
    left_ear="Nourish. Earring",
    waist="Impulse Belt",
    left_ring="Begrudging Ring",
    neck="Nodens Gorget",
    neck="Mizu. Kubikazari",
    ammo="Pemphredo Tathlum",
    left_ring="Trizek Ring",
    left_ear="Lugra Earring +1",
    left_ring="Luzaf's Ring",
    head={ name="Valorous Mask", augments={'Weapon skill damage +5%','Attack+12',}},
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%',}},
    back={ name="Andartia's Mantle", augments={'AGI+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    left_ear="Lugra Earring",
    legs={ name="Lanun Trews", augments={'Enhances "Snake Eye" effect',}},
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+7 "Mag.Atk.Bns."+7','Magic burst dmg.+9%','CHR+5','Mag. Acc.+13','"Mag.Atk.Bns."+4',}},
    legs="Chas. Culottes +1",
    sub={ name="Vampirism", augments={'STR+8','INT+9','"Occult Acumen"+8','DMG:+14',}},
    feet="Hiza. Sune-Ate +1",
    feet="Chass. Bottes +1",
    waist="Chaac Belt",
    hands={ name="Plun. Armlets +1", augments={'Enhances "Perfect Dodge" effect',}},
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    sub={ name="Malevolence", augments={'INT+5','Mag. Acc.+4',}},
    sub={ name="Malevolence", augments={'INT+1','Mag. Acc.+1','"Mag.Atk.Bns."+5',}},
    head="Orion Beret +3",
    back={ name="Andartia's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','"Store TP"+10',}},
    back={ name="Belenus's Cape", augments={'DEX+20','Rng.Acc.+20 Rng.Atk.+20','DEX+10','Crit.hit rate+10',}},
    ammo="Ginsen",
    back={ name="Cichol's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','"Dbl.Atk."+10',}},
    sub="Fettering Blade",
    sub="Demers. Degen +1",
    sub="Perun",
    legs={ name="Vanya Slops", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    left_ring="Rajas Ring",
    sub="Perun +1",
    hands={ name="Herculean Gloves", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Mag. Acc.+9','"Mag.Atk.Bns."+14',}},
    ammo="Animikii Bullet",
    feet="Jhakri Pigaches +1",
    sub="Kustawi +1",
    body="Passion Jacket",
    sub={ name="Taming Sari", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    legs="Orion Braccae +3",
    feet="Orion Socks +3",
    body={ name="Bagua Tunic +1", augments={'Enhances "Bolster" effect',}},
    main={ name="Lathi", augments={'INT+15','"Mag.Atk.Bns."+15','Mag. Acc.+15',}},
    sub={ name="Shijo", augments={'DEX+15','"Dual Wield"+5','"Triple Atk."+2',}},
    range="Dunna",
    feet={ name="Vanya Clogs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10',}},
    head="Azimuth Hood +1",
    body="Sulevia's Plate. +1",
    main="Chango",
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%',}},
    legs="Sulev. Cuisses +2",
    body="Mallquis Saio",
    legs={ name="Herculean Trousers", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Magic burst dmg.+2%','STR+10','"Mag.Atk.Bns."+13',}},
    ammo="Knobkierrie",
    feet="Skulk. Poulaines +1",
    waist="Kentarch Belt +1",
    waist="Metalsinger Belt",
    legs={ name="Herculean Trousers", augments={'Accuracy+5','Crit. hit damage +4%','DEX+13','Rng.Atk.+9',}},
    range="Fomalhaut",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Weapon skill damage +10%',}},
    left_ear="Regal Earring",
    legs={ name="Herculean Trousers", augments={'Rng.Acc.+30','Enmity-3','AGI+15','Rng.Atk.+9',}},
    legs={ name="Adhemar Kecks +1", augments={'AGI+12','Rng.Acc.+20','Rng.Atk.+20',}},
    body={ name="Arc. Jerkin +3", augments={'Enhances "Snapshot" effect',}},
    sub="Enki Strap",
    feet={ name="Agoge Calligae +1", augments={'Enhances "Tomahawk" effect',}},
    feet="Flam. Gambieras +2",
    body={ name="Valorous Mail", augments={'"Dbl.Atk."+3','Accuracy+25','"Store TP"+3','Accuracy+15 Attack+15',}},
    hands="Geo. Mitaines +1",
    legs={ name="Bagua Pants +1", augments={'Enhances "Mending Halation" effect',}},
    feet="Azimuth Gaiters +1",
    neck="Iskur Gorget",
    sub="Mafic Cudgel",
    range="Compensator",
    sub="Chanter's Shield",
    back={ name="Lifestream Cape", augments={'Geomancy Skill +8','Indi. eff. dur. +13','Pet: Damage taken -4%',}},
    left_ear="Mendi. Earring",
    left_ear="Gifted Earring",
    hands={ name="Herculean Gloves", augments={'Accuracy+24 Attack+24','Weapon skill damage +3%','DEX+8','Accuracy+12','Attack+13',}},
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+5 "Mag.Atk.Bns."+5','Magic burst dmg.+7%','CHR+3','Mag. Acc.+15',}},
    hands={ name="Herculean Gloves", augments={'Rng.Acc.+20','Crit. hit damage +4%','AGI+13','Rng.Atk.+13',}},
    back="Mending Cape",
    hands="Orion Bracers +3",
    feet={ name="Pursuer's Gaiters", augments={'Rng.Acc.+10','"Rapid Shot"+10','"Recycle"+15',}},
    back={ name="Belenus's Cape", augments={'"Snapshot"+10',}},
    left_ring="Hetairoi Ring",
    legs={ name="Merlinic Shalwar", augments={'"Mag.Atk.Bns."+22','Magic burst dmg.+10%','INT+9',}},
    feet="Geomancy Sandals",
    head="Meghanada Visor +2",
    hands="Meg. Gloves +2",
    head={ name="Herculean Helm", augments={'Mag. Acc.+18 "Mag.Atk.Bns."+18','Weapon skill damage +4%','MND+3','"Mag.Atk.Bns."+13',}},
    back={ name="Belenus's Cape", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','Weapon skill damage +10%',}},
    main={ name="Grioavolr", augments={'Magic burst dmg.+3%','DEX+7','Mag. Acc.+29','"Mag.Atk.Bns."+30','Magic Damage +3',}},
    body="Meg. Cuirie +2",
    left_ear="Ishvara Earring",
    legs="Meg. Chausses +2",
    feet="Jute Boots +1",
    hands="Sulev. Gauntlets +2",
    feet="Meg. Jam. +2",
    legs={ name="Arc. Braccae +2", augments={'Enhances "Eagle Eye Shot" effect',}},
    body="Amini Caban +1",
    sub="Tanmogayi +1",
    left_ear="Telos Earring",
    feet="Wicce Sabots +1",
    hands={ name="Carmine Fin. Ga. +1", augments={'Rng.Atk.+20','"Mag.Atk.Bns."+12','"Store TP"+6',}},
    head="Boii Mask +1",
    hands={ name="Arc. Bracers +1", augments={'Enhances "Flashy Shot" effect',}},
    hands={ name="Adhemar Wrist. +1", augments={'AGI+12','Rng.Acc.+20','Rng.Atk.+20',}},
    back={ name="Camulus's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
    hands={ name="Vanya Cuffs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    left_ear="Etiolation Earring",
    sub="Utu Grip",
    legs="Amini Brague +1",
    back={ name="Lutian Cape", augments={'STR+1','AGI+3','"Store TP"+2','"Snapshot"+2',}},
    hands="Amini Glovelettes",
    waist="Reiki Yotai",
    left_ear="Thureous Earring",
    left_ring="Regal Ring",
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Store TP"+10',}},
    left_ear="Enervating Earring",
    body={ name="Vanya Robe", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    neck="Lissome Necklace",
    sub="Sors Shield",
    left_ear="Neritic Earring",
    range="Fail-Not",
    feet={ name="Herculean Boots", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','INT+4','"Mag.Atk.Bns."+13',}},
    feet={ name="Herculean Boots", augments={'Weapon skill damage +3%','AGI+11','Rng.Acc.+12','Rng.Atk.+9',}},
    feet={ name="Herculean Boots", augments={'Accuracy+19 Attack+19','"Triple Atk."+3','STR+10','Attack+4',}},
    legs="Pumm. Cuisses +3",
    head="Amini Gapette +1",
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Rng.Acc.+10','"Store TP"+10',}},
    waist="Goading Belt",
    body={ name="Carm. Sc. Mail +1", augments={'Attack+20','"Mag.Atk.Bns."+12','"Dbl.Atk."+4',}},
    waist="Yemaya Belt",
    left_ring="Dingir Ring",
    sub="Nusku Shield",
    left_ring="Meghanada Ring",
    legs="Jhakri Slops +1",
    left_ring="Niqmaddu Ring",
    left_ring="Ilabrat Ring",
    left_ring="Kishar Ring",
    feet={ name="Valorous Greaves", augments={'Accuracy+26','"Store TP"+5',}},
    body="Nisroch Jerkin",
    back={ name="Rudianos's Mantle", augments={'HP+60','Eva.+20 /Mag. Eva.+20','"Fast Cast"+10',}},
    head="Sulevia's Mask +2",
    back={ name="Weard Mantle", augments={'VIT+3','Enmity+5',}},
    left_ring="Supershear Ring",
    head={ name="Carmine Mask", augments={'Accuracy+15','Mag. Acc.+10','"Fast Cast"+3',}},
    neck="Ainia Collar",
    waist="Sailfi Belt +1",
    neck="Incanter's Torque",
    back={ name="Nantosuelta's Cape", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Pet: "Regen"+10',}},
    left_ear="Odnowa Earring +1",
    head={ name="Vanya Hood", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    feet="Boii Calligae +1",
    head={ name="Agoge Mask +1", augments={'Enhances "Savagery" effect',}},
    back="Aurist's Cape",
    left_ear="Sherida Earring",
    feet={ name="Herculean Boots", augments={'Rng.Acc.+20 Rng.Atk.+20','"Snapshot"+2','AGI+8','Rng.Acc.+6','Rng.Atk.+10',}},
    waist="Eschan Stone",
}